version: "3.9"

services:
  backend:
    container_name: backend-dev
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - MONGO_USER=admin
      - MONGO_PASSWORD=password
      - REDIS_PORT=6379
      - JWT_SECRET=secret
      - PORT=8000
    volumes:
      - ./:/app
      - appLogs:/app/logs
      - /app/node_modules
    command: npm run dev

  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - express-mongo
    depends_on:
      - mongodb